Repository beyond-sw-camp/be10-fin-ErrorPirate-OrderBridge, pull requests merged in 2024-12, with the labels that each got.

#11 feat: 부트스트랩 적용
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
Labels: enhancement

#24 feat: 엔티티 생성 및 ERD 수정으로 인한 엔티티 수정
  backend/src/main/java/error/pirate/backend/client/command/domain/aggregate/entity/Client.java
  backend/src/main/java/error/pirate/backend/invoice/command/domain/aggregate/entity/Invoice.java
  backend/src/main/java/error/pirate/backend/invoice/command/domain/aggregate/entity/InvoiceItem.java
  backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/BomItem.java
  backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/Item.java
  backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemDivision.java
  backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemInventory.java
  backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemUnit.java
  backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursement.java
  backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementItem.java
  backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementStatus.java
  backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/aggregate/entity/ProductionReceiving.java
  backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/aggregate/entity/ProductionReceivingItem.java
  backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/Purchase.java
  backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseItem.java
  backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseItemStatus.java
  backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseStatus.java
  backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrder.java
  backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrderItem.java
  backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrderStatus.java
  backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/Quotation.java
  backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/QuotationItem.java
  backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/QuotationStatus.java
  backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrder.java
  backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrderItem.java
  backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrderStatus.java
  backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstruction.java
  backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstructionItem.java
  backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstructionStatus.java
  backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlip.java
  backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlipItem.java
  backend/src/main/java/error/pirate/backend/test/controller/SwaggerTestController.java
  backend/src/main/java/error/pirate/backend/user/command/domain/aggregate/entity/User.java
  backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/Warehouse.java
  backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/WarehouseType.java
  backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
  backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrderStatus.java
Labels: feat

#26 feat: 프론트엔드 견적서 리스트 작성 기능 추가
  frontend/index.html
  frontend/src/App.vue
  frontend/src/components/common/Header.vue
  frontend/src/components/quotation/QuotationList.vue
  frontend/src/router/index.js
  frontend/src/views/quotation/QuotationList.vue
Labels: enhancement

#27 feat: 프론트엔드 입력폼 초안
  frontend/src/components/common/Header.vue
  frontend/src/components/common/InputForm.vue
  frontend/src/components/common/inputItems.vue
  frontend/src/router/index.js
  frontend/src/views/main/MainView.vue
  frontend/src/views/quotation/InputView.vue
Labels: feat

#28 feat: 사이드바 구현
  frontend/src/components/common/SideMenuBar.vue
Labels: feat

#36 feat: 입력폼 초안
  SCM/frontend/src/assets/trashIcon.svg
  SCM/frontend/src/components/common/InputForm.vue
  SCM/frontend/src/components/common/inputItems.vue
  SCM/frontend/src/views/quotation/InputView.vue
Labels: feat

#38 feat: 현황 초안
  SCM/frontend/src/components/common/CurrentSituation.vue
  SCM/frontend/src/router/index.js
Labels: feat

#42 feat: 백엔드 출하지시서 조회 및 상세 조회 구현
  SCM/backend/build.gradle
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/resources/application.yml
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/controller/ShippingInstructionControllerTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/service/ShippingInstructionServiceTest.java
Labels: feat, test

#54 feat: 견적서 현황 조회 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/controller/QuotationQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/mapper/QuotationMapper.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/service/QuotationQueryService.java
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
Labels: enhancement

#55 test: 견적서 조회 테스트 코드 추가
  SCM/backend/src/test/java/error/pirate/backend/quotation/query/service/QuotationQueryServiceTest.java
Labels: test

#51 feat: 작업지시서 목록 조회 및 테스트코드 작성
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/controller/WorkOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderFilterDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/mapper/WorkOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryServiceTest.java
Labels: feat, test

#52 bug: 백엔드 출하지시서 조회 및 상세 조회 오류 수정 및 테스트 진행
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/controller/ShippingInstructionControllerTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/service/ShippingInstructionServiceTest.java
Labels: bug, enhancement

#59 test: 출하지시서 현황 조회 테스트
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionSituationRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryServiceTest.java
Labels: test

#61 feat: 주문서 조회 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/controller/QuotationQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/controller/SalesOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderListItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderResponse.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/mapper/SalesOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/service/SalesOrderQueryService.java
  SCM/backend/src/main/resources/mappers/salesOrder/SalesOrderMapper.xml
Labels: enhancement

#67 feat: 거래 명세서 조회 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/controller/InvoiceQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceDTO.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceListItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceResponse.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/mapper/InvoiceMapper.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/service/InvoiceQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/controller/QuotationQueryController.java
  SCM/backend/src/main/resources/mappers/invoice/InvoiceMapper.xml
Labels: enhancement

#68 feat: 품목 등록 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/item/command/Infrastructure/repository/ItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/Infrastructure/repository/ItemUnitRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemSaveDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/service/ItemService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemDivision.java
  SCM/backend/src/test/java/error/pirate/backend/item/command/application/service/ItemServiceTest.java
Labels: feat, test

#72 feat: 품목 조회 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryContoller.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemFilterDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemSearchDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/mapper/ItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/main/resources/mappers/item/ItemMapper.xml
Labels: feat

#74 feat: 생산입고 리스트 조회 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/config/QueryDSLConfig.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/controller/ProductionReceivingController.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/aggregate/entity/ProductionReceiving.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/aggregate/entity/ProductionReceivingStatus.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/repository/ProductionReceivingRepository.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/controller/ProductionReceivingQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/dto/ProductionReceivingDTO.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/dto/ProductionReceivingListRequest.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/dto/ProductionReceivingListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/repository/ProductionReceivingQueryRepository.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/repository/impl/ProductionReceivingQueryRepositoryImpl.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/service/ProductionReceivingQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlip.java
  SCM/backend/src/test/java/error/pirate/backend/productionReceiving/command/application/service/ProductionReceivingServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/productionReceiving/query/service/ProductionReceivingQueryServiceTest.java
Labels: feat

#73 feat: 품목 수정 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/item/command/Infrastructure/repository/ItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/service/ItemService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/Item.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemUnitRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryContoller.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemFilterRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/mapper/ItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/main/resources/mappers/item/ItemMapper.xml
Labels: feat

#78 refactor: enum 타입 영문으로 수정
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementStatus.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/QuotationStatus.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstructionStatus.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/WarehouseType.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrderStatus.java
Labels: refactor

#80 fix: 견적서 테스트 코드 메소드 명 교체
  SCM/backend/src/test/java/error/pirate/backend/quotation/query/service/QuotationQueryServiceTest.java
Labels: bug

#81 refactor: 출하지시서 조회 mapper 와 테스트 코드 수정
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryServiceTest.java
Labels: refactor

#87 feat: 출하지시서 등록 구현
  SCM/backend/build.gradle
  SCM/backend/src/main/java/error/pirate/backend/exception/CustomException.java
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/exception/GlobalExceptionHandler.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/service/ItemService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrder.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/repository/SalesOrderRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/service/SalesOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/controller/ShippingInstructionCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/dto/ShippingInstructionItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/dto/ShippingInstructionRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstruction.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstructionItem.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/repository/ShippingInstructionItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/repository/ShippingInstructionRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/mapper/ShippingInstructionItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/mapper/ShippingInstructionMapper.java
Labels: enhancement, feat

#91 feat: 출하지시서 수정 구현
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/controller/ShippingInstructionCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstruction.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/repository/ShippingInstructionItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionItemDomainService.java
Labels: feat

#100 feat: 출하지시서 삭제 구현
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/controller/ShippingInstructionCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
Labels: feat

#108 feat: 상세조회 및 현황조회 구현
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/controller/WorkOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/MonthlyWorkOrderSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderFilterDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderResponse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/mapper/WorkOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryServiceTest.java
Labels: enhancement, feat, test, refactor

#110 feat: 생산입고 상태 변경(결재완료, 생산입고완료)
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemInventory.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemInventoryRepository.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/controller/ProductionReceivingController.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/dto/ProductionReceivingUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/service/ProductionReceivingService.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/aggregate/entity/ProductionReceiving.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/aggregate/entity/ProductionReceivingStatus.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrder.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/repository/SalesOrderRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/repository/SalesOrderQueryRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/repository/impl/SalesOrderQueryRepositoryImpl.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
  SCM/backend/src/test/java/error/pirate/backend/productionReceiving/command/application/service/ProductionReceivingServiceTest.java
Labels: feat, test

#112 feat: BOM 등록 및 수정 구현
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/aggregate/entity/Client.java
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/aggregate/entity/Invoice.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/aggregate/entity/InvoiceItem.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/BomItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/service/ItemService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/BomItem.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/Item.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/BomItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursement.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/service/ProductionReceivingService.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/domain/aggregate/entity/ProductionReceiving.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/Purchase.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrder.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/Quotation.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlip.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/Warehouse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
  SCM/backend/src/test/java/error/pirate/backend/item/command/application/service/ItemServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/productionReceiving/command/application/service/ProductionReceivingServiceTest.java
Labels: feat, refactor

#109 feat: 견적서 등록 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/controller/QuotationCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/dto/CreateQuotationRequest.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/dto/QuotationItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/service/QuotationCommandService.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/Quotation.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/QuotationItem.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/repository/QuotationItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/repository/QuotationRepository.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/infrastructure/repository/JpaQuotationItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/infrastructure/repository/JpaQuotationRepository.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationCalculateSumDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/mapper/QuotationMapper.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/service/QuotationQueryService.java
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
Labels: enhancement

#116 feat: 품목 조회 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/BomItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemInventoryRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/BomItemQueryDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemDetailResponse.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemInventoryDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/test/java/error/pirate/backend/item/query/service/ItemQueryServiceTest.java
Labels: feat, test

#127 refactor: 품목조회, 작업지시서 조회 mybatis dtd 링크 수정
  SCM/backend/src/main/resources/mappers/item/ItemMapper.xml
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
Labels: refactor

#133 feat: 품목 삭제 기능 구현 완료
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/service/ItemService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/Item.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemStatus.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemDetailResponse.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemResponse.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/mapper/ItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/main/resources/mappers/item/ItemMapper.xml
Labels: feat

#137 feat: 거래처 삭제 기능 구현 완료
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/controller/ClientController.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/dto/ClientCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/dto/ClientDTO.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/dto/ClientUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/service/ClientService.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/aggregate/entity/Client.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/aggregate/entity/ClientStatus.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/repository/ClientRepository.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/controller/ClientQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/dto/ClientFilterRequest.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/dto/ClientResponse.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/mapper/ClientMapper.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/service/ClientQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/resources/mappers/client/cilentMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/client/command/application/service/ClientServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/client/query/ClientQueryServiceTest.java
Labels: feat, test

#145 refactor: 주문서 PRODUCTION_COMPLETE 로 이름 변경
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/service/ProductionReceivingService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
Labels: refactor

#143 feat: 창고 등록 기능 구현 완료
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/controller/WarehouseController.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/dto/WarehouseCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/dto/WarehouseDTO.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/dto/WarehouseResponse.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/service/WarehouseService.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/Warehouse.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/repository/WarehouseRepository.java
Labels: feat

#149 feat: 창고 수정 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/controller/WarehouseController.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/dto/WarehouseUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/service/WarehouseService.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/Warehouse.java
Labels: feat

#154 refactor: 생산입고조회 조건수정
  SCM/backend/src/test/java/error/pirate/backend/productionReceiving/query/service/ProductionReceivingQueryServiceTest.java
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/productionReceiving/ProductionReceivingList.vue
Labels: refactor

#155 feat: 견적서 수정 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/controller/QuotationCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/dto/QuotationItemUpdateDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/dto/UpdateQuotationRequest.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/service/QuotationCommandService.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/Quotation.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/QuotationItem.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/repository/QuotationItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/repository/QuotationRepository.java
Labels: enhancement

#156 feat: 출하전표 조회/등록/수정/삭제
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrder.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/service/SalesOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/mapper/ShippingInstructionItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionSituationMonthlyTotalDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/controller/ShippingSlipCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/dto/ShippingSlipItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/dto/ShippingSlipRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlip.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlipItem.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlipStatus.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/repository/ShippingSlipItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/repository/ShippingSlipRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/service/ShippingSlipDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/service/ShippingSlipItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/mapper/ShippingSlipItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/mapper/ShippingSlipMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/controller/ShippingSlipQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipListRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipSituationMonthlyTotalDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipSituationRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/mapper/ShippingSlipMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/service/ShippingSlipQueryService.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/main/resources/mappers/shippingSlip/ShippingSlipMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingSlip/query/service/ShippingSlipQueryServiceTest.java
Labels: feat, test, refactor

#162 refactor: 출하지시서명, 출하전표명 포맷 형태 변경 및 메소드명 수정
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/service/ShippingSlipDomainService.java
Labels: refactor

#164 refactor: 라우터 분리
  SCM/frontend/src/router/index.js
  SCM/frontend/src/router/shipping-instruction.js
Labels: refactor

#166 feat: 창고 삭제 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/controller/WarehouseController.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/service/WarehouseService.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/Warehouse.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/aggregate/entity/WarehouseStatus.java
Labels: feat

#169 bug: 라우터 컴포넌트 연결 에러 수정
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionInputView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
Labels: bug

#178 refactor: 작업지시서 상태 complete 로 통합
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/service/ProductionReceivingService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrderStatus.java
Labels: refactor

#181 bug: 출하지시서,출하전표 조회 오류 수정
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/main/resources/mappers/shippingSlip/ShippingSlipMapper.xml
Labels: bug

#182 Feat: 발주서 입력 수정
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/aggregate/repository/ClientRepository.java
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/Item.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/Purchase.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/controller/PurchaseOrderController.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/dto/PurchaseOrderCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/dto/PurchaseOrderItemDto.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/dto/PurchaseOrderUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/service/PurchaseOrderApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrder.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrderItem.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/repository/PurchaseOrderItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/service/PurchaseOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/service/PurchaseOrderItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/user/command/domain/aggregate/entity/User.java
Labels: feat

#184 Feat: 발주서 엑셀다운
  SCM/backend/build.gradle
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/service/ClientService.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/aggregate/repository/ClientRepository.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/repository/ClientRepository.java
  SCM/backend/src/main/java/error/pirate/backend/common/Pagination.java
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/Item.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/service/PurchaseOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/controller/PurchaseOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/dto/PurchaseOrderItemResponse.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/dto/PurchaseOrderResponse.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/mapper/PurchaseOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/service/PurchaseOrderService.java
  SCM/backend/src/main/resources/mappers/purchaseOrder/PurchaseOrderMapper.xml
Labels: feat

#185 refactor: 공통 코드 기반으로 출하지시서와 출하전표 수정
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/service/SalesOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationService.java
Labels: refactor

#187 feat: 출하지시서, 출하전표 엑셀 다운 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/common/ExcelDownLoad.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/service/SalesOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/controller/ShippingSlipQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipListRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/service/ShippingSlipQueryService.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/main/resources/mappers/shippingSlip/ShippingSlipMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingSlip/query/service/ShippingSlipQueryServiceTest.java
Labels: feat, test

#189 feat: 출하지시서 조회 페이지 구현
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionStatus.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/inputItems.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/views/quotation/InputView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
Labels: enhancement, feat

#198 feat: 작업지시서 등록 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/BomItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemInventoryRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/service/BomItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/service/ItemInventoryDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/repository/SalesOrderItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/service/SalesOrderItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/user/command/domain/service/UserDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/domain/service/WarehouseDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/controller/WorkOrderCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/dto/CreateWorkOrderRequest.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/service/WorkOrderService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/repository/WorkOrderRepository.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/service/WorkOrderDomainService.java
  SCM/backend/src/test/java/error/pirate/backend/workOrder/command/application/service/WorkOrderServiceTest.java
Labels: feat, test

#204 feat: 구매서 목록, 상세조회
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseItemStatus.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseStatus.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/controller/PurchaseQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/dto/PurchaseItemResponse.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/dto/PurchaseRequest.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/dto/PurchaseResponse.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/dto/PurchaseResponsePagination.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/mapper/PurchaseMapper.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/service/PurchaseService.java
  SCM/backend/src/main/resources/mappers/purchase/PurchaseMapper.xml
Labels: feat

#202 feat: 생산입고 현황 엑셀 구현
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/controller/ProductionReceivingQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/dto/ProductionReceivingSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/service/ProductionReceivingQueryService.java
  SCM/backend/src/main/resources/mappers/productionReceiving/ProductionReceivingMapper.xml
  SCM/frontend/src/components/productionReceiving/ProductionReceivingList.vue
  SCM/frontend/src/components/productionReceiving/ProductionReceivingSituation.vue
Labels: feat

#211 feat: 출하지시서 등록 페이지 구현
  SCM/frontend/src/components/common/InputItems.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputForm.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputItems.vue
  SCM/frontend/src/views/shippingInstruction/InputView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionInputView.vue
Labels: feat

#205 feat: 구매서 엑셀다운
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/controller/PurchaseQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/service/PurchaseService.java
Labels: feat

#207 feat: 구매서등록
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/controller/PurchaseController.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/dto/PurchaseCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/dto/PurchaseItemDto.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/dto/PurchaseUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/service/PurchaseApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/Purchase.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseItem.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseItemStatus.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/repository/PurchaseItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/repository/PurchaseRepository.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/service/PurchaseDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/service/PurchaseItemDomainService.java
Labels: feat

#210 feat: 백엔드 주문서 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/service/QuotationCommandService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/controller/SalesOrderCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/dto/CreateSalesOrderRequest.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/dto/SalesOrderItemRequest.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/dto/UpdateSalesOrderItemReqest.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/dto/UpdateSalesOrderRequest.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/service/SalesOrderCommandService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrder.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrderItem.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/repository/SalesOrderCommandRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/repository/SalesOrderItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/service/SalesOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/infrastructure/repository/JpaSalesOrderItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/infrastructure/repository/JpaSalesOrderRepository.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderItemCheckDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/mapper/SalesOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/service/SalesOrderQueryService.java
  SCM/backend/src/main/resources/mappers/salesOrder/SalesOrderMapper.xml
Labels: enhancement

#208 feat: 구매서수정
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/controller/PurchaseController.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/service/PurchaseApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/Purchase.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseItem.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/service/PurchaseDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/service/PurchaseItemDomainService.java
Labels: feat

#209 feat: 구매서 삭제 및 상태변경
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/controller/PurchaseController.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/service/PurchaseApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/Purchase.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/service/PurchaseDomainService.java
Labels: feat

#215 refactor: 작업지시서 목록조회 수정
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderFilterDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
Labels: refactor

#216 feat: 출하지시서 현황 조회 페이지 구현 및 백엔드 현황 조회 & 인쇄 로직 수정
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionSituationMonthlyTotalDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/controller/ShippingSlipQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipSituationMonthlyTotalDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/mapper/ShippingSlipMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/service/ShippingSlipQueryService.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/main/resources/mappers/shippingSlip/ShippingSlipMapper.xml
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionSituation.vue
  SCM/frontend/src/router/shipping-instruction.js
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionSituationView.vue
Labels: feat, refactor

#220 feat: 작업지시서 삭제 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/controller/WorkOrderCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/dto/CreateWorkOrderRequest.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/service/WorkOrderService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/service/WorkOrderDomainService.java
Labels: feat

#222 feat: 백엔드 거래 명세서 등록 수정 삭제 기능 개발
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/controller/InvoiceCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/controller/UpdateInvoiceRequest.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/dto/CreateInvoiceItemRequest.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/dto/CreateInvoiceRequest.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/dto/UpdateInvoiceItemRequest.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/service/InvoiceCommandService.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/aggregate/entity/Invoice.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/aggregate/entity/InvoiceItem.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/aggregate/entity/InvoiceStatus.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/repository/InvoiceItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/repository/InvoiceRepository.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/domain/service/InvoiceDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/infrastructure/repository/JpaInvoiceItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/infrastructure/repository/JpaInvoiceRepository.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceItemCheckDTO.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/mapper/InvoiceMapper.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/service/InvoiceQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderItemCheckDTO.java
  SCM/backend/src/main/resources/mappers/invoice/InvoiceMapper.xml
  SCM/backend/src/main/resources/mappers/salesOrder/SalesOrderMapper.xml
Labels: enhancement

#229 feat: 출하지시서 상세 조회 구현
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionItemDTO.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/frontend/src/assets/editIcon.svg
  SCM/frontend/src/assets/printIcon.svg
  SCM/frontend/src/assets/trashIcon.svg
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputItems.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionSituation.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
Labels: enhancement, feat

#228 refactor: 작업지시서 조회 수정
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderFilterDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/mapper/WorkOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
Labels: refactor

#232 refactor: 프론트엔드 출하지시서 조회, 등록 리팩토링 및 백엔드 클래스명 수정
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/dto/ShippingInstructionItemRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/dto/ShippingInstructionRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/mapper/ShippingInstructionItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/dto/ShippingSlipItemRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/dto/ShippingSlipRequest.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/service/ShippingSlipDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/mapper/ShippingSlipItemMapper.java
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationServiceTest.java
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputForm.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputItems.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionInputView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
Labels: test, refactor

#235 feat: Frontend - 견적서 목록 조회 기능 추가
  .gitignore
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/QuotationStatus.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/controller/QuotationQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/mapper/QuotationMapper.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/service/QuotationQueryService.java
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/quotation/query/service/QuotationQueryServiceTest.java
  SCM/frontend/src/axios.js
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/quotation/QuotationList.vue
  SCM/frontend/src/router/index.js
Labels: enhancement, refactor

#236 Feat: 발주서 목록, 상세조회 프론트구현
  SCM/backend/src/main/java/error/pirate/backend/common/Pagination.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/controller/PurchaseOrderController.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/service/PurchaseOrderApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/dto/PurchaseOrderRequest.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/dto/PurchaseOrderResponse.java
  SCM/backend/src/main/resources/mappers/purchaseOrder/PurchaseOrderMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderInputForm.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderInputItems.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderList.vue
  SCM/frontend/src/router/index.js
  SCM/frontend/src/views/purchaseOrder/PurchaseOrderInputView.vue
  SCM/frontend/src/views/purchaseOrder/PurchaseOrderListView.vue
Labels: feat

#237 refactor: 등록 시 불러온 주문서나 출하지시서의 수량 확인 절차 로직
  SCM/backend/src/main/java/error/pirate/backend/common/RemainingQuantity.java
  SCM/backend/src/main/java/error/pirate/backend/common/mapper/CommonMapper.java
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/repository/ShippingInstructionRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionItemCheckDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/resources/mappers/common/CommonMapper.xml
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputItems.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionInputView.vue
Labels: enhancement, refactor

#240 refactor: 목록 조회
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrderStatus.java
  SCM/backend/src/main/resources/mappers/purchase/PurchaseMapper.xml
  SCM/backend/src/main/resources/mappers/purchaseOrder/PurchaseOrderMapper.xml
  SCM/frontend/src/components/purchase/PurchaseList.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderList.vue
Labels: refactor

#243 feat: 견적서 목록 엑셀 다운로드 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/common/ExcelDownLoad.java
  SCM/backend/src/main/java/error/pirate/backend/config/WebConfig.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/domain/aggregate/entity/QuotationStatus.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/controller/QuotationQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationListItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/mapper/QuotationMapper.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/service/QuotationQueryService.java
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/quotation/query/service/QuotationQueryServiceTest.java
  SCM/frontend/src/components/quotation/QuotationList.vue
Labels: enhancement, refactor

#246 feat: 품목 조회 페이지 구현
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemDivision.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemFilterRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/mapper/ItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/main/resources/mappers/item/ItemMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/item/command/application/service/ItemServiceTest.java
  SCM/frontend/src/App.vue
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/router/index.js
  SCM/frontend/src/router/item.js
  SCM/frontend/src/views/item/ItemListView.vue
Labels: feat

#251 refactor: 테이블 및 연관관계 변경에 따른 엔티티 수정
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursement.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementItem.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementStatus.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
Labels: refactor

#259 feat: 작업지시서 목록조회 화면 구현
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementItem.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderFilterDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/mapper/WorkOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/router/index.js
  SCM/frontend/src/router/work-order.js
  SCM/frontend/src/views/workOrder/WorkOrderListView.vue
Labels: enhancement, feat

#263 feat: 견적서 상세 조회 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemDivision.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/frontend/src/components/quotation/QuotationList.vue
Labels: enhancement

#272 feat: 작업지시서 상세 조회 화면 구현 및 인쇄
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderItemDTO.java
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
Labels: enhancement

#273 refactor: 사이드바 통계 수정
  SCM/frontend/src/components/common/SideMenuBar.vue
Labels: refactor

#270 feat: 품목 등록 페이지 구현
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemDivisionResponse.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemUnitResponse.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/controller/WarehouseQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/mapper/WarehouseMapper.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/service/WarehouseQueryService.java
  SCM/backend/src/main/resources/mappers/warehouse/WarehouseMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/router/item.js
  SCM/frontend/src/views/item/ItemListView.vue
  SCM/frontend/src/views/item/IteminputView.vue
Labels: feat

#275 refactor: 추가 리팩토링(enum 들 한글 변경, axios.js 사용, 조회 상세 리스트 디자인 수정)
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/domain/aggregate/entity/SalesOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/controller/SalesOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionEditForm.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionEditItems.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputForm.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputItems.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionEditView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionInputView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionSituationView.vue
Labels: enhancement, refactor

#277 feat: 품목 수정 페이지 구현
  SCM/frontend/src/router/item.js
  SCM/frontend/src/views/item/ItemListView.vue
  SCM/frontend/src/views/item/ItemUpdateView.vue
Labels: feat

#282 feat: 작업지시서 현황조회 화면구현 및 인쇄 구현
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderSituationDTO.java
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/components/workOrder/WorkOrderSituation.vue
  SCM/frontend/src/router/work-order.js
  SCM/frontend/src/views/workOrder/WorkOrderSituationView.vue
Labels: enhancement

#289 bug: 메인화면 및 사이드바 수정
  SCM/frontend/src/App.vue
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/images/img.png
  SCM/frontend/src/views/main/MainView.vue
Labels: bug

#294 bug: 긴급! 주소 클래스 변경 과정에서 엔티티 연결 변경 필요
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/aggregate/entity/ShippingInstruction.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/aggregate/entity/ShippingSlip.java
Labels: bug

#303 feat: 창고 등록 조회 수정 삭제 페이지 구현
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/controller/WarehouseQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/dto/WarehouseFilterRequest.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/dto/WarehouseListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/dto/WarehouseResponse.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/mapper/WarehouseMapper.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/service/WarehouseQueryService.java
  SCM/backend/src/main/resources/mappers/warehouse/WarehouseMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/router/index.js
  SCM/frontend/src/router/warehouse.js
  SCM/frontend/src/views/warehouse/WarehouseListView.vue
  SCM/frontend/src/views/warehouse/WarehouseModifyView.vue
  SCM/frontend/src/views/warehouse/WarehouseinputView.vue
Labels: feat

#302 refactor: 디자인 수정
  SCM/frontend/index.html
  SCM/frontend/src/App.vue
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/quotation/QuotationList.vue
Labels: refactor

#310 feat: 프론트엔드 견적서 삭제 기능 추가
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
  SCM/frontend/src/components/quotation/QuotationInput.vue
  SCM/frontend/src/components/quotation/QuotationList.vue
  SCM/frontend/src/router/index.js
  SCM/frontend/src/router/quotation.js
  SCM/frontend/src/views/quotation/QuotationInputView.vue
Labels: enhancement

#315 feat: 작업지시서 목록, 현황 엑셀 다운로드 구현
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/controller/WorkOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/mapper/WorkOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/components/workOrder/WorkOrderSituation.vue
Labels: enhancement, feat, refactor

#317 feat: 출하전표 등록 및 품목 재고 수정 로직 추가
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/ItemInventory.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemInventoryRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/service/ItemInventoryDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/repository/ShippingInstructionItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/controller/ShippingSlipCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/repository/ShippingSlipRepository.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/service/ShippingSlipDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/domain/service/ShippingSlipItemDomainService.java
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
Labels: enhancement, feat

#321 feat: 거래처 페이지 구현
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/dto/ClientCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/dto/ClientDTO.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/dto/ClientUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/domain/aggregate/entity/Client.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/controller/ClientQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/dto/ClientFilterRequest.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/dto/ClientListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/dto/ClientResponse.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/mapper/ClientMapper.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/service/ClientQueryService.java
  SCM/backend/src/main/resources/mappers/client/cilentMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/client/command/application/service/ClientServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/client/query/ClientQueryServiceTest.java
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/productionReceiving/ProductionReceivingInputForm.vue
  SCM/frontend/src/router/client.js
  SCM/frontend/src/router/index.js
  SCM/frontend/src/views/Client/ClientListView.vue
  SCM/frontend/src/views/Client/ClientModifyView.vue
  SCM/frontend/src/views/Client/ClientinputView.vue
Labels: feat

#324 feat: 작업지시서 등록,수정,삭제 페이지 구현
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/ItemInventoryRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/service/ItemInventoryDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/controller/SalesOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderItemStockStatusResponse.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderListItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/mapper/SalesOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/service/SalesOrderQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/dto/CreateWorkOrderRequest.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/dto/UpdateWorkOrderRequest.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/service/WorkOrderService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrder.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/repository/WorkOrderRepository.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/service/WorkOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/mapper/WorkOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
  SCM/backend/src/main/resources/mappers/salesOrder/SalesOrderMapper.xml
  SCM/backend/src/main/resources/mappers/workOrder/workOrderMapper.xml
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/workOrder/WorkOrderInputForm.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/router/work-order.js
  SCM/frontend/src/views/workOrder/WorkOrderEditView.vue
  SCM/frontend/src/views/workOrder/WorkOrderWriteView.vue
Labels: enhancement, feat, refactor

#333 refactor: 거래처 목록 요청 API 수정에 따른 힌트 로직 변경
  SCM/backend/src/main/java/error/pirate/backend/client/query/controller/ClientQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/mapper/ClientMapper.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/service/ClientQueryService.java
  SCM/backend/src/main/resources/mappers/client/cilentMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/invoice/InvoiceList.vue
  SCM/frontend/src/components/quotation/QuotationList.vue
  SCM/frontend/src/components/salesOrder/SalesOrderList.vue
Labels: bug, refactor

#342 feat: 인쇄 미리보기 모달 구현
  SCM/frontend/src/components/common/PrintPreview.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
Labels: enhancement, feat, refactor

#343 feat: 생산불출 목록조회, 다운로드, 상세조회, 상세출력 구현
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursement.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementStatus.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/controller/ProductionDisbursementQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementListDTO.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementListExcel.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementListResponse.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementResponse.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/mapper/ProductionDisbursementMapper.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/service/ProductionDisbursementQueryService.java
  SCM/backend/src/main/resources/mappers/productionDisbursement/ProductionDisbursementMapper.xml
  SCM/backend/src/main/resources/mappers/workOrder/WorkOrderMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementList.vue
  SCM/frontend/src/components/workOrder/WorkOrderInputForm.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/components/workOrder/WorkOrderSituation.vue
  SCM/frontend/src/router/index.js
  SCM/frontend/src/router/production-disbursement.js
  SCM/frontend/src/router/work-order.js
  SCM/frontend/src/views/productionDisbursement/ProductionDisbursementListView.vue
  SCM/frontend/src/views/productionDisbursement/ProductionDisbursementSituationView.vue
Labels: enhancement, feat, refactor

#341 Feat: 등록 프론트
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/service/ItemInventoryDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/ItemInventoryDTO.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/dto/PurchaseCreateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/service/PurchaseApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/Purchase.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/domain/aggregate/entity/PurchaseItem.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/dto/PurchaseResponse.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/service/PurchaseOrderApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/domain/aggregate/entity/PurchaseOrder.java
  SCM/backend/src/main/resources/mappers/purchase/PurchaseMapper.xml
  SCM/backend/src/main/resources/mappers/purchaseOrder/PurchaseOrderMapper.xml
  SCM/frontend/src/components/purchase/PurchaseInputForm.vue
  SCM/frontend/src/components/purchase/PurchaseInputItems.vue
  SCM/frontend/src/components/purchase/PurchaseList.vue
  SCM/frontend/src/components/purchase/PurchaseSituation.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderInputForm.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderInputItems.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderList.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderSituation.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderStockSituation.vue
  SCM/frontend/src/views/purchase/PurchaseInputView.vue
  SCM/frontend/src/views/purchaseOrder/PurchaseOrderInputView.vue
Labels: feat

#347 refactor: github actions 파일 수정
  .ebextensions/01-app-start.config
  .github/workflows/gradle.yml
  .platform/nginx.conf
  Procfile_back
  Procfile_front
  SCM/backend/build.gradle
  SCM/frontend/package-lock.json
  SCM/frontend/package.json
  SCM/frontend/server.js
  SCM/frontend/src/router/client.js
  SCM/frontend/src/views/client/ClientInputView.vue
  SCM/frontend/src/views/client/ClientListView.vue
  SCM/frontend/src/views/client/ClientModifyView.vue
  order_bridgeDDL.sql
Labels: enhancement, refactor

#355 feat: 테스트 커밋
  .github/workflows/gradle.yml
  Procfile_front
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/controller/ClientController.java
  SCM/frontend/package.json
  SCM/frontend/server.js
Labels: bug

#348 refactor: 디자인 리팩토링
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionSituation.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipList.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipSituation.vue
  SCM/frontend/src/views/shippingInstruction/InputView.vue
Labels: refactor

#353 fix: 시큐리티 설정으로 인한 엑셀 다운로드 cors 이슈 해결
  SCM/backend/src/main/java/error/pirate/backend/config/SecurityConfig.java
Labels: bug

#352 feat: 생산불출 현황조회, 다운로드 기능 구현 완료
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/controller/ProductionDisbursementQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/MonthlyProductionDisbursementSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementSituationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/mapper/ProductionDisbursementMapper.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/service/ProductionDisbursementQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/controller/WorkOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderSlipDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderSlipItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderSlipResponse.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/mapper/WorkOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryService.java
  SCM/backend/src/main/resources/mappers/productionDisbursement/ProductionDisbursementMapper.xml
  SCM/backend/src/main/resources/mappers/workOrder/WorkOrderMapper.xml
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementSituation.vue
  SCM/frontend/src/components/workOrder/WorkOrderInputForm.vue
  SCM/frontend/src/views/productionDisbursement/ProductionDisbursementSituationView.vue
Labels: enhancement, feat, refactor

#357 refactor: 엑셀 관련 리팩토링 및 테스트 코드 점검
  SCM/backend/src/main/java/error/pirate/backend/common/ExcelDownLoad.java
  SCM/backend/src/main/java/error/pirate/backend/security/AuthUtil.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/controller/ShippingInstructionCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/domain/service/ShippingInstructionDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/mapper/ShippingInstructionMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/controller/ShippingSlipCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/controller/ShippingSlipQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/mapper/ShippingSlipMapper.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/service/ShippingSlipQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/user/command/domain/service/UserDomainService.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/main/resources/mappers/shippingSlip/ShippingSlipMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/query/service/ShippingInstructionQueryServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/shippingSlip/query/service/ShippingSlipQueryServiceTest.java
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/stores/UserStore.js
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionEditView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionSituationView.vue
  SCM/frontend/src/views/shippingSlip/ShippingSlipListView.vue
  SCM/frontend/src/views/shippingSlip/ShippingSlipSituationView.vue
Labels: test, refactor

#365 refactor: 엑세스 토큰 만료 시 로직 수정
  SCM/backend/src/main/java/error/pirate/backend/security/filter/JwtFilter.java
  SCM/frontend/src/axios.js
Labels: bug

#366 Feat: 전자결재
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/dto/PurchaseOrderResponse.java
  SCM/backend/src/main/resources/mappers/purchaseOrder/PurchaseOrderMapper.xml
  SCM/frontend/package-lock.json
  SCM/frontend/package.json
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderList.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderPrintPreview.vue
  SCM/frontend/src/main.js
Labels: feat

#369 refactor: 챗봇 중첩 입력 막기와 입력란 남아있는 상태 변경
  SCM/backend/src/main/java/error/pirate/backend/chatbot/controller/ChatbotController.java
  SCM/backend/src/main/java/error/pirate/backend/client/command/application/controller/ClientController.java
  SCM/backend/src/main/java/error/pirate/backend/client/query/controller/ClientQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/controller/InvoiceCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/dto/UpdateInvoiceRequest.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/service/InvoiceCommandService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/notification/command/application/controller/NotificationController.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/command/application/controller/ProductionReceivingController.java
  SCM/backend/src/main/java/error/pirate/backend/productionReceiving/query/controller/ProductionReceivingQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/command/application/controller/PurchaseController.java
  SCM/backend/src/main/java/error/pirate/backend/purchase/query/controller/PurchaseQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/controller/PurchaseOrderController.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/controller/PurchaseOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/controller/ShippingInstructionCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/controller/ShippingInstructionQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/controller/ShippingSlipCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/controller/ShippingSlipQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/user/command/application/controller/UserController.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/command/application/controller/WarehouseController.java
  SCM/backend/src/main/java/error/pirate/backend/warehouse/query/controller/WarehouseQueryController.java
  SCM/frontend/src/components/common/Chatbot.vue
  SCM/frontend/src/components/purchase/PurchaseList.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderList.vue
  SCM/frontend/src/views/warehouse/WarehouseListView.vue
  SCM/frontend/src/views/warehouse/WarehouseModifyView.vue
  SCM/frontend/src/views/warehouse/WarehouseinputView.vue
Labels: refactor

#370 docs: README.md
  README.md
Labels: documentation

#371 bug: 헤더 수정
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderInputForm.vue
  SCM/frontend/src/main.js
Labels: bug

#372 feat: s3 이미지 업로드
  SCM/backend/build.gradle
  SCM/backend/src/main/java/error/pirate/backend/common/FileUploadUtil.java
  SCM/backend/src/main/java/error/pirate/backend/config/S3Config.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/service/ItemService.java
  SCM/backend/src/main/resources/application.yml
  SCM/frontend/src/components/item/ItemInputForm.vue
  SCM/frontend/src/views/item/ItemListView.vue
  SCM/frontend/src/views/warehouse/WarehouseListView.vue
  SCM/frontend/src/views/warehouse/WarehouseModifyView.vue
  SCM/frontend/src/views/warehouse/WarehouseinputView.vue
Labels: feat

#374 feat: Frontend - 견적서 등록 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/controller/QuotationCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/dto/CreateQuotationRequest.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/command/application/service/QuotationCommandService.java
  SCM/frontend/src/components/quotation/QuotationInput.vue
  SCM/frontend/src/components/quotation/QuotationList.vue
Labels: enhancement

#375 refactor: 품목 등록 수정
  SCM/frontend/src/components/item/ItemInputForm.vue
Labels: refactor

#379 feat: 생산불출 등록, 수정, 삭제 구현
  SCM/backend/src/main/java/error/pirate/backend/exception/ErrorCodeType.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/repository/BomItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/service/BomItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/service/ItemDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/dto/BomItemQueryDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/mapper/ItemMapper.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/application/controller/ProductionDisbursementController.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/application/dto/CreateAndUpdateProductionDisbursementRequest.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/application/dto/ProductionDisbursementItemRequest.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/application/service/ProductionDisbursementService.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursement.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/entity/ProductionDisbursementItem.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/repository/ProductionDisbursementItemRepository.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/repository/ProductionDisbursementRepository.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/service/ProductionDisbursementDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/controller/WorkOrderCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/service/WorkOrderService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/aggregate/entity/WorkOrderStatus.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/service/WorkOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/controller/WorkOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderListDTO.java
  SCM/backend/src/main/resources/mappers/item/ItemMapper.xml
  SCM/backend/src/main/resources/mappers/productionDisbursement/ProductionDisbursementMapper.xml
  SCM/backend/src/main/resources/mappers/workOrder/WorkOrderMapper.xml
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementInputForm.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementList.vue
  SCM/frontend/src/components/workOrder/WorkOrderInputForm.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/router/production-disbursement.js
  SCM/frontend/src/views/productionDisbursement/ProductionDisbursementEditView.vue
  SCM/frontend/src/views/productionDisbursement/ProductionDisbursementWriteView.vue
Labels: enhancement, feat, refactor

#382 refactor: system_instruction.txt 파일 추가
  .gitignore
  SCM/backend/src/main/resources/system_instruction.txt
Labels: refactor

#383 feat: 전자결재 기능구현
  SCM/backend/src/main/java/error/pirate/backend/common/FileUploadUtil.java
  SCM/backend/src/main/java/error/pirate/backend/notification/command/application/controller/NotificationController.java
  SCM/backend/src/main/java/error/pirate/backend/notification/command/application/dto/SignRequest.java
  SCM/backend/src/main/java/error/pirate/backend/notification/command/domain/aggregate/entity/Notification.java
  SCM/backend/src/main/java/error/pirate/backend/notification/command/domain/aggregate/entity/NotificationType.java
  SCM/backend/src/main/java/error/pirate/backend/notification/command/domain/repository/NotificationRepository.java
  SCM/backend/src/main/java/error/pirate/backend/notification/command/domain/service/NotificationDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/command/application/service/PurchaseOrderApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/controller/PurchaseOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/mapper/PurchaseOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/purchaseOrder/query/service/PurchaseOrderService.java
  SCM/backend/src/main/resources/mappers/purchaseOrder/PurchaseOrderMapper.xml
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderPrintPreview.vue
Labels: feat
