Repository beyond-sw-camp/be10-fin-ErrorPirate-OrderBridge, pull requests merged in 2025-01, with the labels that each got.

#387 feat: 주문서 등록 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationResponse.java
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
  SCM/frontend/src/common/salert.js
  SCM/frontend/src/components/quotation/QuotationInput.vue
  SCM/frontend/src/components/quotation/QuotationList.vue
  SCM/frontend/src/components/salesOrder/SalesOrderInput.vue
  SCM/frontend/src/components/salesOrder/SalesOrderList.vue
  SCM/frontend/src/router/salesOrder.js
  SCM/frontend/src/views/salesOrder/SalesOrderInputView.vue
Labels: enhancement

#396 feat: Frontend - 거래 명세서 등록 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/controller/InvoiceCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/command/application/service/InvoiceCommandService.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/controller/SalesOrderCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/command/application/service/SalesOrderCommandService.java
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/components/invoice/InvoiceInput.vue
  SCM/frontend/src/components/invoice/InvoiceList.vue
  SCM/frontend/src/components/quotation/QuotationInput.vue
  SCM/frontend/src/components/salesOrder/SalesOrderInput.vue
  SCM/frontend/src/router/invoice.js
  SCM/frontend/src/views/invoice/InvoiceInputView.vue
Labels: enhancement

#399 feat: Backend - 거래 명세서 목록 엑셀 다운로드 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/controller/InvoiceQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/dto/InvoiceExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/mapper/InvoiceMapper.java
  SCM/backend/src/main/java/error/pirate/backend/invoice/query/service/InvoiceQueryService.java
  SCM/backend/src/main/resources/mappers/invoice/InvoiceMapper.xml
  SCM/frontend/src/components/invoice/InvoiceList.vue
Labels: enhancement

#398 feat: Backend - 주문서 목록 엑셀 다운로드 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/controller/SalesOrderQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/mapper/SalesOrderMapper.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/service/SalesOrderQueryService.java
  SCM/backend/src/main/resources/mappers/salesOrder/SalesOrderMapper.xml
Labels: enhancement

#405 feat: 출하지시서, 출하전표 등록 시 알림 기능
  SCM/backend/src/main/java/error/pirate/backend/notification/command/domain/aggregate/entity/NotificationType.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/controller/ShippingInstructionCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingInstruction/query/dto/ShippingInstructionDTO.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/command/application/service/ShippingSlipApplicationService.java
  SCM/backend/src/main/java/error/pirate/backend/shippingSlip/query/dto/ShippingSlipDTO.java
  SCM/backend/src/main/resources/mappers/shippingInstruction/ShippingInstructionMapper.xml
  SCM/backend/src/main/resources/mappers/shippingSlip/ShippingSlipMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/shippingInstruction/command/application/service/ShippingInstructionApplicationServiceTest.java
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputForm.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionPrintPreview.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionSituation.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipList.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipPrintPreview.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipSituation.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionSituationView.vue
  SCM/frontend/src/views/shippingSlip/ShippingSlipListView.vue
  SCM/frontend/src/views/shippingSlip/ShippingSlipSituationView.vue
Labels: enhancement, feat, refactor

#406 feat: Frontend - 견적서 현황 조회 기능 추가
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/controller/QuotationQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationSituationExcelDTO.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/dto/QuotationSituationResponse.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/mapper/QuotationMapper.java
  SCM/backend/src/main/java/error/pirate/backend/quotation/query/service/QuotationQueryService.java
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
  SCM/frontend/src/components/quotation/QuotationSituation.vue
  SCM/frontend/src/router/quotation.js
  SCM/frontend/src/views/quotation/QuotationSituationView.vue
Labels: enhancement

#413 refactor: 견적서, 주문서, 거래 명세서 입력 폼 스타일 변경
  SCM/frontend/src/components/invoice/InvoiceInput.vue
  SCM/frontend/src/components/quotation/QuotationInput.vue
  SCM/frontend/src/components/salesOrder/SalesOrderInput.vue
Labels: refactor

#415 refactor: 작업지시서, 생산불출 등록/수정기능 수정
  SCM/backend/src/main/java/error/pirate/backend/notification/command/domain/aggregate/entity/NotificationType.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/dto/SalesOrderItemStockStatusResponse.java
  SCM/backend/src/main/java/error/pirate/backend/salesOrder/query/service/SalesOrderQueryService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/service/WorkOrderService.java
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementInputForm.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementList.vue
  SCM/frontend/src/components/workOrder/WorkOrderInputForm.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/views/workOrder/WorkOrderEditView.vue
Labels: bug, refactor

#416 refactor: 알림 디자인 수정
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderList.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderPrintPreview.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionPrintPreview.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipList.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipPrintPreview.vue
Labels: refactor

#411 feat: 이미지 s3 구현
  SCM/backend/src/main/java/error/pirate/backend/common/OctetStreamReadMsgConverter.java
  SCM/backend/src/main/java/error/pirate/backend/config/WebConfig.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/controller/ItemController.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemDTO.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/dto/ItemUpdateRequest.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/application/service/ItemService.java
  SCM/backend/src/main/java/error/pirate/backend/item/command/domain/aggregate/entity/Item.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/item/query/service/ItemQueryService.java
  SCM/backend/src/test/java/error/pirate/backend/item/command/application/service/ItemServiceTest.java
  SCM/frontend/src/components/item/ItemInputForm.vue
  SCM/frontend/src/views/item/ItemListView.vue
Labels: feat

#421 refactor: 품목 조회 수정 완료
  SCM/backend/src/main/resources/mappers/item/ItemMapper.xml
  SCM/frontend/src/views/item/ItemListView.vue
Labels: refactor

#422 fix: 견적서, 주문서, 거래 명세서 - 배포 환경 비즈니스 로직 테스트 결과 수정
  SCM/backend/src/main/resources/mappers/invoice/InvoiceMapper.xml
  SCM/backend/src/main/resources/mappers/quotation/QuotationMapper.xml
  SCM/backend/src/main/resources/mappers/salesOrder/SalesOrderMapper.xml
  SCM/frontend/src/axios.js
  SCM/frontend/src/common/salert.js
  SCM/frontend/src/components/invoice/InvoiceList.vue
  SCM/frontend/src/components/quotation/QuotationInput.vue
  SCM/frontend/src/components/salesOrder/SalesOrderInput.vue
  SCM/frontend/src/components/salesOrder/SalesOrderList.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionPrintPreview.vue
  SCM/frontend/src/components/shippingSlip/ShippingSlipPrintPreview.vue
  SCM/frontend/src/router/index.js
  SCM/frontend/src/stores/UserStore.js
Labels: bug, refactor

#425 refactor: 작업지시서, 생산불출 출력 모달로 변경, 결재, 알림 기능 구현
  SCM/backend/src/main/java/error/pirate/backend/item/query/controller/ItemQueryController.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/application/controller/ProductionDisbursementController.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/application/service/ProductionDisbursementService.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/command/domain/aggregate/service/ProductionDisbursementDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/dto/ProductionDisbursementDetailDTO.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/controller/WorkOrderCommandController.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/application/service/WorkOrderService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/command/domain/service/WorkOrderDomainService.java
  SCM/backend/src/main/java/error/pirate/backend/workOrder/query/dto/WorkOrderDetailDTO.java
  SCM/backend/src/main/resources/mappers/productionDisbursement/ProductionDisbursementMapper.xml
  SCM/backend/src/main/resources/mappers/workOrder/WorkOrderMapper.xml
  SCM/backend/src/test/java/error/pirate/backend/workOrder/command/application/service/WorkOrderServiceTest.java
  SCM/backend/src/test/java/error/pirate/backend/workOrder/query/service/WorkOrderQueryServiceTest.java
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementInputForm.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementList.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementPrintPreview.vue
  SCM/frontend/src/components/workOrder/WorkOrderInputForm.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/components/workOrder/WorkOrderPrintPreview.vue
Labels: bug, enhancement, feat, refactor

#432 refactor: 헤더, 사이드바, 메인 이미지 수정
  SCM/frontend/src/components/common/Header.vue
  SCM/frontend/src/components/common/SideMenuBar.vue
  SCM/frontend/src/views/main/MainView.vue
Labels: refactor

#436 refactor: alert 공통 코드 적용
  SCM/frontend/src/common/salert.js
  SCM/frontend/src/components/invoice/InvoiceInput.vue
  SCM/frontend/src/components/invoice/InvoiceList.vue
  SCM/frontend/src/components/invoice/InvoiceSituation.vue
  SCM/frontend/src/components/item/ItemInputForm.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementInputForm.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementList.vue
  SCM/frontend/src/components/productionDisbursement/ProductionDisbursementSituation.vue
  SCM/frontend/src/components/productionReceiving/ProductionReceivingInputForm.vue
  SCM/frontend/src/components/productionReceiving/ProductionReceivingList.vue
  SCM/frontend/src/components/purchase/PurchaseInputForm.vue
  SCM/frontend/src/components/purchase/PurchaseList.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderInputForm.vue
  SCM/frontend/src/components/purchaseOrder/PurchaseOrderList.vue
  SCM/frontend/src/components/quotation/QuotationInput.vue
  SCM/frontend/src/components/quotation/QuotationList.vue
  SCM/frontend/src/components/quotation/QuotationSituation.vue
  SCM/frontend/src/components/salesOrder/SalesOrderInput.vue
  SCM/frontend/src/components/salesOrder/SalesOrderList.vue
  SCM/frontend/src/components/salesOrder/SalesOrderSituation.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionEditItems.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionInputItems.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/components/workOrder/WorkOrderInputForm.vue
  SCM/frontend/src/components/workOrder/WorkOrderList.vue
  SCM/frontend/src/components/workOrder/WorkOrderSituation.vue
  SCM/frontend/src/views/client/ClientInputView.vue
  SCM/frontend/src/views/client/ClientListView.vue
  SCM/frontend/src/views/client/ClientModifyView.vue
  SCM/frontend/src/views/item/ItemListView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionEditView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionInputView.vue
  SCM/frontend/src/views/shippingInstruction/ShippingInstructionListView.vue
  SCM/frontend/src/views/user/LoginView.vue
  SCM/frontend/src/views/warehouse/WarehouseListView.vue
  SCM/frontend/src/views/warehouse/WarehouseModifyView.vue
  SCM/frontend/src/views/warehouse/WarehouseinputView.vue
Labels: refactor

#441 refactor: 디자인 이슈 수정
  SCM/frontend/src/components/common/Chatbot.vue
  SCM/frontend/src/components/shippingInstruction/ShippingInstructionList.vue
  SCM/frontend/src/views/salesOrder/SalesOrderSituationView.vue
Labels: refactor

#447 refactor: README.md 수정
  README.md
Labels: refactor

#448 docs: 리드미 erd 링크 수정, 요구사항 명세서 파일 수정
  README.md
  SCM/backend/src/main/java/error/pirate/backend/productionDisbursement/query/controller/ProductionDisbursementQueryController.java
  gif/요구사항 명세서.pdf
  img/요구사항 명세서.jpg
Labels: documentation
